function getRandomGreeting() {
  var greetings = [
    "Beep boop! Are you a robot?",
    "Did you know I have a discord server?",
    "How many sides does a circle have?",
    "You can read btw",
    "Made you look!",
    "Redbull gives you wings...",
    "Since 2025!",
    "As seen on TV!",
    "doot doot 677777777777777777777777777777777777777777777777777777777777777777777",
    "Cold as ice!",
    "Made in the US!",
    "Made by gollclock!",
    "WARNING: You may lose braincells if you proceed!",
    "Do you bite your ice cream?",
    "#Relatable",
    "Fortnite is cringe",
    "You got games on your phone?",
    "Powered by hamsters!",
    "*insert cool explosion*",
    "Got to go fast!",
    "My Laptop passcode is 563543 btw",
    "Sponsered by RAID SHADOW LEGENDS!",
    "Sponsored by Honey!",
    "Sponsored by gollclock!",
    "Powered by 128 Gigs of RAM!",
    "Powered by 16MB of RAM!",
    "w h a t",
    "gollclock.github.io is here!",
    "what the dog doin?",
    "I'm gonna pop some tags",
    "Shoutout to G!",
    "thx stackoverflow!",
    "are you a gaemer?",
    "We didn't start the fire! It was always burning, since the world's been turning!",
    "Don't ask questions if you can't handle the answers!",
    "If you are using Duck Duck Go or Yahoo, you need some help.",
    "Living in Spain without the S",
    "Shoutout to gollclock",
    "Woo! /g/",
    "youtube.com/watch?v=dQw4w9WgXcQ",
    "youtube.com/@3kh0",
    "Is this the United Airlines costumer service center?",
    "POV that one person who's 2 braincells are fighting for second place.",
    "bottem text",
    "Why do they call it oven if you oven the cold food of out hot eat the food",
    "No fun allowed",
    "Your toes will be pulled tonight",
    "i do love buying birth certificates from the black market! - Said You",
    "'If you are trash go play Fortnite you loser' - Sun Tzu, Art of war",
    "i wanted free vbucks :(",
    "Avocados \ud83e\udd51 from Mexico \ud83c\uddf2\ud83c\uddfd",
    "reload for another message",
    "He stomped on his fruit loops and thus became a cereal killer.",
    "And just to think I knew him before he was famous",
    "Trust me, I did not copy Minecraft with this",
    "It is everyday bro",
    "That proves you are unusual",
    "What's my age again?",
    "This is the 5th time this week, and it's only Monday",
    "You bum",
    "Roblox? Cringe!",
    "Toss the Turtle is pretty fun",
    "Mission failed, we will get them next time",
    "NUKE INCOMING!",
    "I spent too much time making these",
  ];
  var randomIndex = Math.floor(Math.random() * greetings.length);
  return greetings[randomIndex];
}

document.getElementById("subtitle").innerText = getRandomGreeting();
